# -*- coding: utf-8 -*-
"""Prob-Stat-1.1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yS4tPQhXzYU_02PTyZtsSZ9yB5d02FX1
"""

# Program to compute measures of central tendency and dispersion
import statistics
import math

# Input dataset
data = [100,123,457,690,723,624,1040]
print("Dataset:", data)

# Mean
mean = sum(data) / len(data)
print("\nMean =", mean)

# Median
median = statistics.median(data)
print("Median =", median)

# Mode
mode = statistics.mode(data)
print("Mode =", mode)

# Range
data_range = max(data) - min(data)
print("Range =", data_range)

# Variance
variance = statistics.variance(data)
print("Variance =", variance)

# Standard Deviation
std_dev = statistics.stdev(data)
print("Standard Deviation =", std_dev)